patches von (Moritz Both)

diff --git a/shell/prearc.in b/shell/prearc.in
--- a/shell/prearc.in
+++ b/shell/prearc.in
@@ -10,14 +10,6 @@
 #
 #   Privileges: laeuft bei mir derzeit als root (daher auch chown...)
 #
-#   Bugs:   Um Race-Conditions zu vermeiden werden die Rohdaten in ein
-#	    temporaeres Directory verschoben, das nach dem Arcen radikal
-#	    geloescht wird. Falls zwischenzeitlich etwas schief ging,
-#	    fuehrt das zu Datenverlusten.
-#
-#		Jemand, der sich besser mit /bin/sh auskennt, moege sich
-#		mal gelegentlich darum kuemmern...
-#
 
 LOCK=@SPOOLDIR@/locks/prearc.lck
 
@@ -80,56 +72,25 @@ do
 
 	# System nur bearbeiten, wenn (a) kein Netcall laeuft und (b) Arbeit
 	# vorhanden ist
+	WRK=`ls *.prv *.brt 2>/dev/null`
 	WRK="`find . -type f ! -name \*.lck -print`"
 	if [ \( ! -r $NETLOCK \) -a \(  "$WRK" != "" \) ]; then
-		mkdir $TMP
-		mv $WRK $TMP 2> /dev/null
-		cd $TMP
-		if [ $fmt = "ZNETZ" ]
-		then
-			auspack $arc ../../$sys
-			for zcon in *.prv *.eil *.neu *.brt
-			do
-				if [ -r $zcon ]
-				then
-					net38export $zcon puffer
-				fi
-			done
-			einpack $arc ../../$sys puffer
-			OK=$?
-			if [ $OK -eq 0 ]
-			then
-				chown @USER@ ../../$sys.* 2> /dev/null
-				rm -f *
-			fi
-		fi
 		if [ $fmt = "JANUS" ]
 		then
-			einpack $arc ../../$sys *
+			if einpack $arc ../$sys $WRK; then
+				rm -f $WRK
+			else
+				echo "$0: einpack $arc ../$sys $WRK failed" >&2
+			fi
 			OK=$?
-			chown @USER@ ../../$sys.* 2>/dev/null
+			chown @USER@ ../$sys.* 2>/dev/null
 		fi
 		if [ $fmt = "ZCONNECT" ]
 		then
-			einpack $arc ../../prv.$sys *.prv *.eil *.neu 2>/dev/null
-			OK=$?
-			if [ $OK -eq 0 ]
-			then
-				einpack $arc ../../brt.$sys *.brt 2>/dev/null
-				OK=$?
-			fi
-			if [ $OK -eq 0 ]
-			then
-				chown @USER@ ../../brt.$sys.* 2>/dev/null
-				chown @USER@ ../../prv.$sys.* 2>/dev/null
-			fi
-		fi
-		cd ..
-		if [ $OK -ne 0 ]
-		then
-			echo Prearc: Dateien nicht geloescht. System: $sys
-		else
-			rm -rf $TMP
+			einpack $arc ../prv.$sys *.prv *.eil *.neu 2>/dev/null
+			einpack $arc ../brt.$sys *.brt 2>/dev/null
+			chown @USER@ ../brt.$sys.* 2>/dev/null
+			chown @USER@ ../prv.$sys.* 2>/dev/null
 		fi
 	fi
 
